name: Build and Release SVN Manager

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install oracledb
        pip install tkinterdnd2

    - name: Compile Application
      run: |
        bash compile_app.sh

    - name: Read Version
      id: get_version
      run: echo "VERSION=$(cat latest_version.txt)" >> $GITHUB_ENV

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: "${{ env.VERSION }}"
        name: "SVN Manager ${{ env.VERSION }}"
        files: dist/SVNManager.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
